### ISSUE TITLE
Help compiling to wasm

### ISSUE THREAD

**Issue by noluben** [imgui-rs/imgui-rs#447]
I am new to Rust; but interested in using imgui-rs. Is it possible to generate wasm output? I changed Cargo.toml in imgui-examples folder; changed
 **imgui = { path = "../imgui" }**
to
  **imgui = { path = "../imgui",  version = "0.7.0", features = ["wasm"] }**

Compiling failed. I am looking for an example how to do this.

Thanks
Jasmeer

**Comment by dbr** [comment]
https://github.com/selassje/nes-rs is using imgui-rs (0.7) and emscripten to run in a browser

However the author of that created #563 which implies that there are issues around this (although the issue is a few years old, not sure if it's still applicable)

**Comment by dbr** [comment]
Mostly a note to myself:

I quickly tried building `nes-rs` as-is and had weird errors with unrelated things,
```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at memset (nes_rs.wasm:0x59b68a)
    at nes_rs::io::io_internal::IOInternal::new::he159866eab55d0e0 (nes_rs.wasm:0x168330)
    at invoke_i (nes-rs.js:10674:36)
    at nes_rs::io::io_sdl2_imgui_opengl::IOSdl2ImGuiOpenGl::new::hf272b6d9f0d0dc75 (nes_rs.wasm:0x14a18)
    at nes_rs::Emulation::new::hf8fb8fe306f04c26 (nes_rs.wasm:0x2283c)
    at nes_rs::main::h065658b1da01b6e1 (nes_rs.wasm:0xfb70)
    at core::ops::function::FnOnce::call_once::h7f8b4d629627a3ec (nes_rs.wasm:0xff04)
    at std::sys_common::backtrace::__rust_begin_short_backtrace::h1d6139903e40827a (nes_rs.wasm:0x1064a)
    at std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h52a685667d128efe (nes_rs.wasm:0xfa97)
    at invoke_ii (nes-rs.js:10586:36)
```

..which I suspect is because I'm using a newer emscripten SDK (3.1.30 when it was tested with 2.0), or something in the Rust `wasm32-unknown-emscripten` toolchain

As a sanity-check, I did make some actual progress:

1. starting with random-recently-made-thing-which-uses-emscripten, https://github.com/permutationlock/raylib_wasm_rs_example (at rev e385e6e43c7824768c182cce8aadf437df6d2745 )
2. shoved in `imgui = "0.10.0"` (not using `wasm` feature)
3. shoved in some basic usage of `imgui` (basically just `imgui::Context::create()`, setting `display_size` and generating-and-ignoring the font atlas, then debug-log the draw-data's vertex count

..and it works, displaying some sane vertex count. So imgui-rs itself compiles fairly trivially (and we can possibly remove the `wasm` feature flag - I'm not exactly sure why this was added, it was from https://github.com/imgui-rs/imgui-rs/pull/322 which just explains the change as "should reduce Embark's divergence with upstream and not be in the way for anybody else")

I guess next step would be to find an reasonably up-to-date example of using glow under wasm/emscripten (https://github.com/grovesNL/glow/blob/main/examples/hello/src/main.rs might be it, also egui's eframe)

**Comment by dbr** [comment]
Hmm so it seems emscripten support has fallen out of favour in Rust-land and isn't well supported. It was mentioned in a few random articles it was "deprecated" which I think isn't the right way of describing it (as emscripten itself is still quite actively developed), it's just no longer supported by quite a few Rust crates. E.g winit [no longer supports it at all](https://github.com/rust-windowing/winit/issues/2391), glow [does](https://github.com/grovesNL/glow/pull/195) but it's not clear how to actually use this in practice as it's [WASM example](https://github.com/grovesNL/glow/tree/d7037ef557e70ade837ae9e3c25122069bf88474/examples/hello) uses `wasm32-unknown-unknown` with `wasm-bindgen`, etc.

I think it could be made to work (haven't explored this direction further, but most probably `wgpu-hal` would be a good next step), but "no longer preferred way in Rust ecosystem" would likely mean this path involve forking a bunch of projects which isn't really a good direction here

The better supported way forward seems to be `wasm32-wasi` (or `wasm32-unknown-unknown` with `wasm-bindgen`) - the tricky part being how to compile the C++ parts, for which the answer seems to be https://github.com/WebAssembly/wasi-sdk for which there there is a [convinience wrapper wasienv](https://github.com/wasienv/wasienv) (although I found it initially a bit opaque in what it is doing - the CLI has no help, steps have no obvious verbose output to explain what they are actually doing), but.. it builds without errors:

```
$ python -m venv wasienv
$ source wasienv/bin/activate
$ pip install wasmenv
...

(wasienv) $ wasienv install-sdk unstable
(wasienv) $ cd imgui-rs/imgui
(wasienv) $ wasiconfigure cargo build --target wasm32-wasi
   Compiling imgui-sys v0.10.0 (/home/dbr/code/vendor/imgui-rs/imgui-sys)
[...some minor looking warnings..]
    Finished dev [unoptimized + debuginfo] target(s) in 6.59s
```

Next step is trying to connect this up with `glow` which also builds under the same target

**Comment by Rob2309** [comment]
I just spent a few hours trying to make imgui-rs work with wasm32-unknown-unknown.
I managed to get it to load correctly in a browser by

- compiling a basic crate with a few wasm-bindgen exported functions that call imgui functions
- enabling the imgui wasm feature
- compiling cimgui manually with emscripten
- hacking together those two wasm modules in a js script

This at least allows correct imgui::Context::new() calls. However, creating the font atlas always gives me some "memory access out of bounds" error in the console. This is, however, not a big surprise as wasm32-unknown-unknown and emscripten are not ABI compatible. Nevertheless I wanted to test this setup at least once.

I am planning on trying a wasm32-wasi setup soon.

**Comment by Rob2309** [comment]
Ok this turned out to be more cumbersome than I imagined.

Compiling for wasm32-wasi works after setting a few flags to use the correct sysroot. The problem here is that wasm-bindgen is not compatible, meaning WebGl is not really an option.

Compiling for wasm32-unknown-unknown does not work because the compiled C++ code will use an incompatible ABI, breaking everything at runtime.

I tried working with wasm32-wasi and changing the code to not trigger any panics in wasm-bindgen, but this has not been successful yet. As far as I can tell, this should theoretically work as long as no wasm-bindgen enabled function passes structs by value, but I am not sure.

**Comment by Rob2309** [comment]
![](https://i.imgur.com/EfK6ADD.png)

Ok it seems I finally found a way to successfully use imgui-rs with wasm32-unknown-unknown, writeup will follow.
Spoiler: This is completely unfeasible for production right now.

**Comment by Rob2309** [comment]
So what I did can be summarized as:
- compile cimgui with wasm32-wasi
- make every cimgui function ABI compatible with wasm32-unknown-unknown
- compile the rust code with wasm32-unknown-unknown

The actual setup is a bit more complicated though.

The first problem is making cimgui ABI compatible with the rust code. This means making every function that takes a struct by value take it by pointer instead. This can be achieved by modifying the cimgui generator in a few places and following imgui update procedure outlined in the imgui-rs doc files.

The second problem arises because ImGui relies on a few standard C functions (e.g. vsnprintf). The first solution one might try is simply linking with -lc, but this somehow breaks the metadata generated by wasm-bindgen (still no idea why). Thus, the solution I chose was implementing the functions ImGui uses by myself. The IO functions (e.g. fopen) and many others don't need to do anything useful. A special case was the `malloc` and `free` functions, which I hooked up to the corresponding functions generated by wasm-bindgen.

For building cimgui with wasm32-wasi as target while building the rest with wasm32-unknown-unknown, I used a .cargo/config.toml file:
```toml
[env]
CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_LINKER="<wasi-sdk>/bin/wasm-ld"
CC_wasm32-unknown-unknown="<wasi-sdk>/bin/clang"
CXX_wasm32-unknown-unknown="<wasi-sdk>/bin/clang++"
CXXFLAGS_wasm32-unknown-unknown="-I<wasi-sdk>/share/wasi-sysroot/include --target=wasm32-wasi"

[build]
rustflags = ["-C", "link-args=-L<wasi-sdk>/share/wasi-sysroot/lib/wasm32-wasi"]
```
I am not sure that this is the optimal config file, but it seems to work for now.

Next, the imgui-glow-renderer is not compatible with wasm. In order to work I had to take out the GlStateBackup code as well as a few other code snippets.

Finally, I compiled everything with `wasm-pack build --target=web`. At this point, this should compile without errors.

Then I wrote a simple entry point:
```rust
use glow::HasContext;
use wasm_bindgen::prelude::wasm_bindgen;
use web_sys::WebGl2RenderingContext;

pub struct App {
    imgui: imgui::Context,
    renderer: imgui_glow_renderer::AutoRenderer,
}

#[wasm_bindgen]
impl App {
    #[wasm_bindgen(constructor)]
    pub fn new(gl: WebGl2RenderingContext) -> Self {
        let mut imgui = imgui::Context::create();

        let glow = glow::Context::from_webgl2_context(gl);
        let renderer = imgui_glow_renderer::AutoRenderer::initialize(glow, &mut imgui).unwrap();

        Self {
            imgui,
            renderer,
        }
    }

    pub fn frame(&mut self, width: u32, height: u32) {
        self.imgui.io_mut().display_size = [width as _, height as _];
    
        let ui = self..imgui.frame();

        let mut open = true;
        ui.show_demo_window(&mut open);

        let draw_data = self.imgui.render();
        self.renderer.render(draw_data).unwrap();
    }
}
```

This entry point can then finally be used to render to a `<canvas>`, yielding the result in the previous comment.

I am not sure if this is helpful in any way, but I couldn't accept the fact that basic interop between Rust and C in wasm is basically impossible.

**Comment by coderedart** [comment]
My advice would be to give up on wasm32-unknown-unknown.

I wanted lua scripting for egui on wasm. anyway, to use c binding crates, we have to go with emscripten target. After a lot of reading, I was able to get egui/lua/sdl2 or glfw/glow working on emscripten target. 
live sample: https://coderedart.github.io/rust-sdl2-wasm/ or https://coderedart.github.io/egui_glow_glfw_emscripten/

code is at https://github.com/coderedart/rust-sdl2-wasm . I think you will find it super easy to understand. the only crucial part is to add a couple emscripten flags inside `.cargo/config` and everything else should be super obvious (including the workflow). you can easily replace the egui part with imgui and basically be done. 

Anyway, I am working on a crate called egui_backend where i am trying to abstract away window and graphics backends of egui into traits. part of that work was trying to also allow sdl2/glfw backends to be used on emscripten. I was just wondering if i could make the backends neutral for egui/imgui/yakui etc.. as all of them follow the same core architecture in terms of window input and gfx output. This will allow a winit/sdl2/glfw backend as well as wgpu/vulkan/glow etc..  backends to be shared by all those projects.

If anyone  wants to help with this, please reach out. I am just getting started on separating out the egui parts and could use some help adding imgui parts. I will steal whatever i can from existing imgui backends in this repo for now.

**Comment by Rob2309** [comment]
I have now managed to modify wasm-bindgen to properly support the wasm32-wasi ABI. With this I was able to get imgui-rs working in the browser without any changes to imgui-sys, which is easier than the previous solution.

Apart from the GLStateBackup and GLSL version parsing, the imgui-glow-renderer works pretty well.

**Comment by Rob2309** [comment]
The corresponding PR https://github.com/rustwasm/wasm-bindgen/pull/3324 in wasm-bindgen is now open.

**Comment by happydpc** [comment]
> The corresponding PR [rustwasm/wasm-bindgen#3324](https://github.com/rustwasm/wasm-bindgen/pull/3324) in wasm-bindgen is now open.

Nice work, how doese this works with Rust side shims? with some function wrapped in rust call, then we can compile to wasm-unknown-unknown

**Comment by happydpc** [comment]
> 

Oh, I see, With this wasm-bindgen PR, it can be compiled whithout any changes.  What I mean is like [this PR](https://github.com/gyscos/zstd-rs/pull/139), that can be built whith some wasm shim to replace specific functions.

**Comment by Rob2309** [comment]
> > 
> 
> 
> 
> Oh, I see, With this wasm-bindgen PR, it can be compiled whithout any changes.  What I mean is like [this PR](https://github.com/gyscos/zstd-rs/pull/139), that can be built whith some wasm shim to replace specific functions.

I see, I think this would be more in the scope of specific crates instead of wasm-bindgen.
