### ISSUE TITLE
Glow renderer issue on macOS

### ISSUE THREAD

**Issue by toyboot4e** [imgui-rs/imgui-rs#533]
**Describe the bug**
The 01_basic example panics on macOS.

**To Reproduce**

On macOS, `cd` into `imgui-glow-renderer` and run `cargo run --example 01_basic`:

<details><summary>Output</summary>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `/Users/tbm/ghq/github.com/toyboot4e/imgui-rs/target/debug/examples/01_basic`
thread 'main' panicked at 'called glDebugMessageInsert but it was not loaded.', /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:4232:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0035d9dcecee49d1f7349932bfa52c05a6f83641/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/0035d9dcecee49d1f7349932bfa52c05a6f83641/library/std/src/panicking.rs:460:5
   2: glow::gl46::go_panic_because_fn_not_loaded
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:4232:5
   3: glow::gl46::call_atomic_ptr_6arg
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:4378:17
   4: glow::gl46::struct_commands::GlFns::DebugMessageInsert
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/gl46.rs:10422:23
   5: <glow::native::Context as glow::HasContext>::debug_message_insert
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.10.0/src/native.rs:2026:9
   6: imgui_glow_renderer::gl_debug_message
             at ./src/lib.rs:1089:9
   7: imgui_glow_renderer::Renderer::render
             at ./src/lib.rs:276:9
   8: imgui_glow_renderer::AutoRenderer::render
             at ./src/lib.rs:117:9
   9: _01_basic::main::{{closure}}
             at ./examples/01_basic.rs:58:17
  10: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/app_state.rs:100:13
  11: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/app_state.rs:78:13
  12: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/app_state.rs:99:9
  13: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/app_state.rs:205:21
  14: winit::platform_impl::platform::app_state::AppState::handle_redraw
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/app_state.rs:352:9
  15: winit::platform_impl::platform::view::draw_rect
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/view.rs:353:9
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <() as objc::message::MessageArguments>::invoke
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  33: objc::message::platform::send_unverified
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  34: objc::message::send_message
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  35: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/event_loop.rs:177:22
  36: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/macos/event_loop.rs:144:9
  37: winit::event_loop::EventLoop<T>::run
             at /Users/tbm/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:154:9
  38: _01_basic::main
             at ./examples/01_basic.rs:31:5
  39: core::ops::function::FnOnce::call_once
             at /rustc/0035d9dcecee49d1f7349932bfa52c05a6f83641/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Expected behavior**
The example runs without errors.

**Please describe your environment**
 - On [the lastest commit][C] in the master branch
 - macOS Big Sur 11.0.1

[C]: https://github.com/imgui-rs/imgui-rs/commit/a6b61be583a01508a54bb76fdc1b029cf8c41f44

**Comment by toyboot4e** [comment]
Ok, it looks like OpenGL on mac does not support debug assertion. I tried disabling `gl_extensions_support` and it worked.

<img width="1136" alt="imgui-glow-macos" src="https://user-images.githubusercontent.com/47905926/133881148-e61f9977-b3f4-45bc-85c1-53571bc53166.png">

The DPI scaling needs to be fixed though.

**Comment by toyboot4e** [comment]
Resizing the window is cursed. It might be glutin issue though

https://user-images.githubusercontent.com/47905926/133881816-379d6efd-1a07-40ef-83d1-f56353852e1c.mov

**Comment by sanbox-irl** [comment]
check out #534 for how to fix the examples working. I'll take a look at resizing tomorrow! DPI + Winit is a ~whole~ thing. Maybe it's in a new situation, but I remember winit being very opinionated on DPI

**Comment by thomcc** [comment]
> being very opinionated on DPI

It's ~~terrible~~ opinions here are a large part of why I don't use winit myself, almost ever. But I've fought about this in discord a lot in the past (closer to when those changes were made, admittedly), and have no energy to continue that fight...

**Comment by toyboot4e** [comment]
Hi, thank you for your answers, quick fix and sharing the info!

`winit` is an awesome library, but windowing seems to be so hard..

I'm closing the issue, since it is more of `winit` issue. I personally use SDL so never mind. But I do want to use a `winit` based engine, so any info share will be appreciated :) Or, hopefully  I can do it myself. Thank you as always!!
